version: "3.9"
services:
  database:
    image: postgres:13.3
    volumes:
      - blog4j-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blog4j
  app:
    build: .
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      - "BLOG4J_BLOG_HEADER=Example Blog"
      - "BLOG4J_BLOG_FOOTER=Example Blog"
      - "BLOG4J_BLOG_TITLE=Example Blog"
      - "BLOG4J_BLOG_DOMAIN=example.com"
      - TZ=Europe/Berlin
volumes:
  blog4j-data:
